name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: test secrets
            echo SERVER_HOST "${{ secrets.SERVER_HOST }}"
            echo SERVER_USERNAME "${{ secrets.SERVER_USERNAME }}"
            echo SSH_PORT "${{ secrets.SSH_PORT }}"
            echo SSH_PRIVATE_KEY "${{secrets.SSH_PRIVATE_KEY }}"
            echo SSH_PASS "${{ secrets.SSH_PASS }}"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: "s344.xrea.com"
          # host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASS }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            git pull origin main
